version: "2.1"
networks: {}
volumes:
  data-store: {}
services:
  main:
    build:
      context: .
    privileged: true
    tty: true
    restart: always
    network_mode: host
    volumes:
      - "data-store:/usr/src/app/drive"
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
